version: '3'

services:
  web:
    build: .
    volumes:
      - .:/web_django
    ports:
      - '8000:8000'
    links:
      - postgresql
    depends_on:
      - postgresql

  postgresql:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=deals_user_pwd
      - POSTGRES_HOST=postgresql
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
